// Generated by scripts/generate_audio_session_abi.py; do not edit.
localparam [15:0] AUDIO_ABI_VERSION = 16'h0002;
localparam [31:0] AUDIO_CONTROL_ADDR = 32'h30140100;
localparam [31:0] AUDIO_CONTROL_MAGIC = 32'h4d414354;
localparam [31:0] AUDIO_CONTROL_COMMIT_ADDR = 32'h30140128;
localparam [31:0] AUDIO_CONTROL_COMMIT_MAGIC = 32'h4d414343;
localparam [31:0] AUDIO_STATUS_ADDR = 32'h30140140;
localparam [31:0] AUDIO_STATUS_MAGIC = 32'h4d415354;
localparam [31:0] AUDIO_STATUS_COMMIT_ADDR = 32'h30140178;
localparam [31:0] AUDIO_STATUS_COMMIT_MAGIC = 32'h4d415343;
