#!/usr/bin/env python3
"""Generate the audio mailbox constants from the authoritative host ABI."""
import argparse
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = root / "tests/frozen-host/mailbox_abi_spec.hpp"
target = root / "fpga/Plex_MiSTer/rtl/audio_session_abi.svh"
names = {
    "kAudioSessionAbiVersion": ("AUDIO_ABI_VERSION", 16),
    "kAudioControlAddr": ("AUDIO_CONTROL_ADDR", 32),
    "kAudioControlMagic": ("AUDIO_CONTROL_MAGIC", 32),
    "kAudioControlCommitAddr": ("AUDIO_CONTROL_COMMIT_ADDR", 32),
    "kAudioControlCommitMagic": ("AUDIO_CONTROL_COMMIT_MAGIC", 32),
    "kAudioStatusAddr": ("AUDIO_STATUS_ADDR", 32),
    "kAudioStatusMagic": ("AUDIO_STATUS_MAGIC", 32),
    "kAudioStatusCommitAddr": ("AUDIO_STATUS_COMMIT_ADDR", 32),
    "kAudioStatusCommitMagic": ("AUDIO_STATUS_COMMIT_MAGIC", 32),
}
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
text = source.read_text()
lines = ["// Generated by scripts/generate_audio_session_abi.py; do not edit."]
for name, (rtl, width) in names.items():
    match = re.search(rf"\b{name}\s*=\s*(0x[0-9a-fA-F]+|[0-9]+)u?\s*;", text)
    if not match:
        raise SystemExit(f"missing authoritative constant: {name}")
    value = int(match[1], 0)
    lines.append(f"localparam [{width-1}:0] {rtl} = {width}'h{value:0{width//4}x};")
output = "\n".join(lines) + "\n"
if args.check:
    if not target.exists() or target.read_text() != output:
        raise SystemExit("audio_session_abi.svh is stale; run scripts/generate_audio_session_abi.py")
else:
    target.write_text(output)
