module h264_baseline_syntax_tb_top #(
	parameter bit FAULT_RARE_P8X8 = 1'b0
) (
	input  wire              clk,
	input  wire              reset,
	input  wire              clear,
	input  wire [1:0]        mode,
	input  wire [15:0]       start_bit,
	input  wire [4:0]        nal_unit_type,
	input  wire [1:0]        nal_ref_idc,
	input  wire [4:0]        log2_max_frame_num,
	input  wire [4:0]        log2_max_pic_order_cnt_lsb,
	input  wire [2:0]        poc_type_in,
	input  wire signed [7:0] pps_pic_init_qp,
	input  wire              pps_deblock_ctrl,
	input  wire [7:0]        active_slice_type,
	input  wire signed [7:0] qp_in,
	input  wire [2:0]        num_ref_idx_l0_active_minus1,
	input  wire              in_valid,
	input  wire [7:0]        in_byte,
	input  wire              in_last,
	output wire              in_ready,
	output wire              valid,
	output wire              error,
	output wire              unsupported,
	output wire              busy,
	output wire [15:0]       rbsp_bits_consumed,
	output wire [7:0]        pps_id,
	output wire [7:0]        sps_id,
	output wire              entropy_cabac,
	output wire [7:0]        num_ref_idx_l0_default_minus1,
	output wire signed [7:0] pic_init_qp,
	output wire signed [4:0] chroma_qp_index_offset,
	output wire              deblock_ctrl,
	output wire [15:0]       first_mb_in_slice,
	output wire [7:0]        slice_type,
	output wire [15:0]       frame_num,
	output wire [15:0]       pic_order_cnt_lsb,
	output wire [15:0]       idr_pic_id,
	output wire signed [7:0] slice_qp_delta,
	output wire signed [7:0] slice_qp,
	output wire [1:0]        disable_deblocking_idc,
	output wire signed [7:0] slice_alpha_c0_offset_div2,
	output wire signed [7:0] slice_beta_offset_div2,
	output wire [15:0]       macroblock_bit_offset,
	output wire [15:0]       mb_skip_run,
	output wire              mb_skipped,
	output wire [7:0]        mb_type,
	output wire [3:0]        partition_mode,
	output wire [15:0]       intra4x4_pred_mode_flags,
	output wire [47:0]       intra4x4_rem_modes,
	output wire [2:0]        intra_chroma_pred_mode,
	output wire [5:0]        coded_block_pattern,
	output wire signed [7:0] mb_qp_delta,
	output wire signed [7:0] mb_qp,
	output wire [15:0]       residual_bit_offset
);
	wire [3:0] partition_mode_raw;

	h264_baseline_syntax_parser parser (
		.clk(clk), .reset(reset), .clear(clear),
		.mode(mode), .start_bit(start_bit), .nal_unit_type(nal_unit_type), .nal_ref_idc(nal_ref_idc),
		.log2_max_frame_num(log2_max_frame_num), .log2_max_pic_order_cnt_lsb(log2_max_pic_order_cnt_lsb),
		.poc_type_in(poc_type_in), .pps_pic_init_qp(pps_pic_init_qp), .pps_deblock_ctrl(pps_deblock_ctrl),
		.active_slice_type(active_slice_type), .qp_in(qp_in), .num_ref_idx_l0_active_minus1(num_ref_idx_l0_active_minus1),
		.in_valid(in_valid), .in_byte(in_byte), .in_last(in_last), .in_ready(in_ready),
		.valid(valid), .error(error), .unsupported(unsupported), .busy(busy), .rbsp_bits_consumed(rbsp_bits_consumed),
		.pps_id(pps_id), .sps_id(sps_id), .entropy_cabac(entropy_cabac),
		.num_ref_idx_l0_default_minus1(num_ref_idx_l0_default_minus1), .pic_init_qp(pic_init_qp),
		.chroma_qp_index_offset(chroma_qp_index_offset), .deblock_ctrl(deblock_ctrl),
		.first_mb_in_slice(first_mb_in_slice), .slice_type(slice_type), .frame_num(frame_num),
		.pic_order_cnt_lsb(pic_order_cnt_lsb), .idr_pic_id(idr_pic_id), .slice_qp_delta(slice_qp_delta), .slice_qp(slice_qp),
		.disable_deblocking_idc(disable_deblocking_idc), .slice_alpha_c0_offset_div2(slice_alpha_c0_offset_div2),
		.slice_beta_offset_div2(slice_beta_offset_div2), .macroblock_bit_offset(macroblock_bit_offset),
		.mb_skip_run(mb_skip_run), .mb_skipped(mb_skipped), .mb_type(mb_type), .partition_mode(partition_mode_raw),
		.intra4x4_pred_mode_flags(intra4x4_pred_mode_flags), .intra4x4_rem_modes(intra4x4_rem_modes),
		.intra_chroma_pred_mode(intra_chroma_pred_mode), .coded_block_pattern(coded_block_pattern),
		.mb_qp_delta(mb_qp_delta), .mb_qp(mb_qp), .residual_bit_offset(residual_bit_offset)
	);

	assign partition_mode = FAULT_RARE_P8X8 && (partition_mode_raw == 4'd5) ? 4'd2 : partition_mode_raw;
endmodule
