// 2-PPC product scaler TB top — mapper + tap window + dual bilin.
`default_nettype none

module present_scale_4_3_2ppc_tb (
	input  wire        clk,
	input  wire        reset,
	input  wire        ce_pix,
	input  wire [10:0] hc_g,
	input  wire [10:0] py,
	input  wire        in_content,
	input  wire [7:0]  tap_y0_0,
	input  wire [7:0]  tap_y0_1,
	input  wire [7:0]  tap_y0_2,
	input  wire [7:0]  tap_y0_3,
	input  wire [7:0]  tap_y1_0,
	input  wire [7:0]  tap_y1_1,
	input  wire [7:0]  tap_y1_2,
	input  wire [7:0]  tap_y1_3,
	output wire [10:0] tap_base_x,
	output wire [10:0] store_x0,
	output wire [10:0] store_x1_a,
	output wire [10:0] store_x0_b,
	output wire [10:0] store_x1_b,
	output wire [10:0] store_y0,
	output wire [10:0] store_y1,
	output wire [1:0]  phase_x0,
	output wire [1:0]  phase_x1,
	output wire [1:0]  phase_y,
	output wire [8:0]  wx0_a,
	output wire [8:0]  wx1_a,
	output wire [8:0]  wx0_b,
	output wire [8:0]  wx1_b,
	output wire [8:0]  wy0,
	output wire [8:0]  wy1,
	output wire [7:0]  pix0,
	output wire [7:0]  pix1,
	output wire        de_r,
	output wire        out_valid
);
	present_scale_4_3_2ppc dut (
		.clk(clk),
		.reset(reset),
		.ce_pix(ce_pix),
		.hc_g(hc_g),
		.py(py),
		.in_content(in_content),
		.tap_y0_0(tap_y0_0),
		.tap_y0_1(tap_y0_1),
		.tap_y0_2(tap_y0_2),
		.tap_y0_3(tap_y0_3),
		.tap_y1_0(tap_y1_0),
		.tap_y1_1(tap_y1_1),
		.tap_y1_2(tap_y1_2),
		.tap_y1_3(tap_y1_3),
		.tap_base_x(tap_base_x),
		.store_x0(store_x0),
		.store_x1_a(store_x1_a),
		.store_x0_b(store_x0_b),
		.store_x1_b(store_x1_b),
		.store_y0(store_y0),
		.store_y1(store_y1),
		.phase_x0(phase_x0),
		.phase_x1(phase_x1),
		.phase_y(phase_y),
		.wx0_a(wx0_a),
		.wx1_a(wx1_a),
		.wx0_b(wx0_b),
		.wx1_b(wx1_b),
		.wy0(wy0),
		.wy1(wy1),
		.pix0(pix0),
		.pix1(pix1),
		.de_r(de_r),
		.out_valid(out_valid)
	);
endmodule

`default_nettype wire
