// GENERATED by scripts/gen_core_identity_stamp.py — do not hand-edit.
// SOURCE_GIT=48df5e2942509c1208d81f8ca7cdf304d7af3735
// Regenerate: python3 scripts/gen_core_identity_stamp.py
`ifndef CORE_IDENTITY_STAMP_SVH
`define CORE_IDENTITY_STAMP_SVH
localparam [27:0] CORE_IDENTITY_PROVENANCE_LP = 28'h48DF5E2;
localparam [0:0]  CORE_IDENTITY_CAP_DDR_LP    = 1'b1;
localparam [0:0]  CORE_IDENTITY_CAP_SPI_LP    = 1'b0;
localparam [1:0]  CORE_IDENTITY_ABI_LP        = 2'd1;
localparam [31:0] CORE_IDENTITY_MAGIC_LP      = 32'h504C5843;
localparam [31:0] CORE_IDENTITY_HI_LP         = 32'h548DF5E2;
`endif
