// GENERATED by scripts/gen_core_identity_stamp.py — do not hand-edit.
// SOURCE_GIT=d4dc5d92831d678e79c076408356c9b87ebbb026
// Regenerate: python3 scripts/gen_core_identity_stamp.py
`ifndef CORE_IDENTITY_STAMP_SVH
`define CORE_IDENTITY_STAMP_SVH
localparam [27:0] CORE_IDENTITY_PROVENANCE_LP = 28'hD4DC5D9;
localparam [0:0]  CORE_IDENTITY_CAP_DDR_LP    = 1'b1;
localparam [0:0]  CORE_IDENTITY_CAP_SPI_LP    = 1'b0;
localparam [1:0]  CORE_IDENTITY_ABI_LP        = 2'd1;
localparam [31:0] CORE_IDENTITY_MAGIC_LP      = 32'h504C5843;
localparam [31:0] CORE_IDENTITY_HI_LP         = 32'h5D4DC5D9;
`endif
