// Auto-generated by scripts/gen_rbf_build_id_vh.py — do not hand-edit.
// commit=7d2f0d8a1d6d61db57d00ce430bff3acdc0b9430 dirty=1 qip_count=64
`ifndef PLEX_RBF_BUILD_ID_PARAMS_VH
`define PLEX_RBF_BUILD_ID_PARAMS_VH
`define PLEX_RBF_COMMIT_PREFIX 32'h7D2F0D8A
`define PLEX_RBF_GIT_DIRTY     1'b1
`define PLEX_RBF_QIP_COUNT     16'd64
`endif
