#!/usr/bin/env bash
# Pre-fit elaboration/synthesis check (parent ruling 3, condition 4).
#
# Runs Quartus Analysis & Synthesis ONLY -- no place-and-route, no RBF -- to
# answer "is this module actually in the design?" in minutes instead of the
# ~6 hours a full fit costs. Quartus is elaboration-aware, so this settles the
# cases the regex reachability checker gets wrong in BOTH directions:
#   * instantiation inside a disabled `if (0)` generate  (regex says yes, truth no)
#   * escaped identifiers `\name `                       (regex says no,  truth yes)
#   * file tracked in git but absent from files.qip      (regex cannot see it)
#
# This is NOT a fit and does not consume the fit authorization. It does use the
# remote Quartus slot, so it still respects the one-at-a-time rule.
#
# Usage:
#   scripts/check_prefit_elaboration.sh SLOT [--require MODULE]... \
#       [--under PARENT] [--forbid-only-under PARENT]
#
# Exit codes: 0 all required present · 1 missing/masked · 2 refusal · 77 skip
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT="$ROOT/fpga/Plex_MiSTer"
HOST="${MISTER_REMOTE_HOST:-docker}"

if [[ $# -lt 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  sed -n '2,20p' "${BASH_SOURCE[0]}"
  exit 0
fi
SLOT="$1"; shift
if [[ ! "$SLOT" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo "Invalid slot '$SLOT'" >&2; exit 2
fi
PARSE_ARGS=("$@")
if [[ ${#PARSE_ARGS[@]} -eq 0 ]]; then
  echo "Scope: 0 required modules -- nothing asserted"
  echo "REFUSED: pass at least one --require MODULE"
  exit 2
fi

echo "Scope: project=$PROJECT slot=$SLOT host=$HOST assertions=${#PARSE_ARGS[@]}"

if ! ssh -o BatchMode=yes -o ConnectTimeout=10 "$HOST" true 2>/dev/null; then
  echo "SKIP: remote build host '$HOST' unreachable"
  exit 77
fi

REMOTE_HOME="$(ssh "$HOST" 'printf "%s\n" "$HOME"')"
REMOTE_SLOT="${MISTER_REMOTE_BASE:-$REMOTE_HOME/mplex-builds}/$SLOT"
REMOTE_PROJECT="$REMOTE_SLOT/Plex_MiSTer"
LOCAL_OUT="$PROJECT/remote_out/$SLOT"
mkdir -p "$LOCAL_OUT"

# The slot directory must exist before rsync will populate it.
ssh "$HOST" "mkdir -p '$REMOTE_PROJECT'" || { echo "remote mkdir failed" >&2; exit 1; }

rsync -a --delete --delete-excluded \
  --exclude '/db/' --exclude '/incremental_db/' --exclude '/output_files/' \
  --exclude '/remote_out/' --exclude '/greybox_tmp/' --exclude '/build/' \
  --exclude '*.qws' \
  "$PROJECT/" "$HOST:$REMOTE_PROJECT/"
rs=$?
if [[ $rs -ne 0 ]]; then echo "rsync failed rc=$rs" >&2; exit 1; fi

ssh "$HOST" bash -s -- "$REMOTE_SLOT" "$REMOTE_PROJECT" <<'REMOTE' \
  > "$LOCAL_OUT/prefit.log" 2>&1
set -uo pipefail
remote_slot="$1"; remote_project="$2"
lock="$remote_slot/.build-lock"
mkdir -p "$remote_slot"
if ! mkdir "$lock" 2>/dev/null; then
  echo "SLOT_LOCKED $remote_slot"; exit 75
fi
trap 'rmdir "$lock" 2>/dev/null || true' EXIT
source "$HOME/misterfpga-dev/scripts/lib.sh"; load_env
# Analysis & Synthesis only -- the same front end the real build runs, so the
# elaborated hierarchy is the fit's hierarchy. quartus_fit / quartus_asm are
# deliberately NOT run, so no placement, no routing, no RBF.
# build_id.v is generated by the PRE_FLOW_SCRIPT_FILE, which only fires on a
# full `--flow compile`. Invoke it explicitly with the same argument positions
# Quartus uses (args: <flow> <project> <revision>) or A&S dies at Plex.sv:48.
docker run --rm -v "$remote_project":/build -w /build -u "$(id -u):$(id -g)" \
  "$QUARTUS_IMAGE" sh -c \
  'quartus_sh -t sys/build_id.tcl compile Plex Plex && quartus_map Plex'
echo "QUARTUS_MAP_RC=$?"
REMOTE
srv=$?
tail -3 "$LOCAL_OUT/prefit.log" 2>/dev/null
if grep -q SLOT_LOCKED "$LOCAL_OUT/prefit.log" 2>/dev/null; then
  echo "SKIP: remote slot busy"; exit 77
fi

map_rc=$(grep -oP '(?<=QUARTUS_MAP_RC=)\d+' "$LOCAL_OUT/prefit.log" | tail -1)
echo "quartus_map rc=${map_rc:-unknown} (ssh rc=$srv)"
if [[ "${map_rc:-1}" != "0" ]]; then
  echo "Analysis & Synthesis FAILED -- see $LOCAL_OUT/prefit.log"
  grep -iE '^Error|Error \(' "$LOCAL_OUT/prefit.log" | head -10
  exit 1
fi

rsync -a "$HOST:$REMOTE_PROJECT/output_files/Plex.map.rpt" "$LOCAL_OUT/" 2>/dev/null
if [[ ! -f "$LOCAL_OUT/Plex.map.rpt" ]]; then
  echo "SKIP: no Plex.map.rpt produced"; exit 77
fi

python3 "$ROOT/scripts/check_map_hierarchy.py" "$LOCAL_OUT/Plex.map.rpt" "${PARSE_ARGS[@]}"
exit $?
