#!/usr/bin/env python3
"""Generate the Quartus build-identity stamp for the Plex core.

The MiSTer OSD sidebar shows the CONF_STR ``V`` entry, which is the only
build identity a user can read off the screen while the core is running.
That string is produced by ``fpga/Plex_MiSTer/sys/build_id.tcl`` during the
Quartus pre-flow.

The remote fit rsyncs only ``fpga/Plex_MiSTer/`` to the build slot and then
compiles inside a container at ``/build``. There is no ``.git`` there, so
``git rev-parse`` inside ``build_id.tcl`` cannot see the repository and every
remote build would otherwise be stamped ``nogit`` — an identity that is
identical for every build made on the same day. This script runs on the
developer/CI host, where the repository *is* visible, and writes the stamp
into the project directory so it travels with the rsync.

The stamp carries three independent identifiers:

``DATE``  build date, ``YYMMDD``
``GIT``   short commit of the tree being fitted, suffixed ``D`` when dirty
``SRC``   short digest over the exact source files handed to Quartus

``SRC`` is the honest, non-forgettable half: it is derived from the fitted
sources themselves, so it changes whenever the bitstream inputs change even
if git bookkeeping is wrong, absent, or reused. ``GIT`` alone cannot do that
(a dirty tree, a detached copy, or a rebuilt tag all reuse a commit id).

A true self-md5 of the finished ``.rbf`` cannot be embedded in the fabric: the
hash would cover the bits that display it. The honest split used here is
"source identity in the fabric, artifact md5 in the manifest", and
``scripts/rbf_provenance.py`` joins the two after the fit.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROJECT = ROOT / "fpga" / "Plex_MiSTer"
STAMP_NAME = "build_id_stamp.txt"

# Mirrors the rsync exclude list in scripts/build_rbf_remote.sh: these are
# Quartus outputs/scratch, not fit inputs, and must not perturb SRC.
EXCLUDED_DIRS = {"db", "incremental_db", "output_files", "remote_out", "greybox_tmp", "build"}
EXCLUDED_SUFFIXES = {".qws"}
# Generated by the pre-flow from this very stamp; including either would make
# SRC self-referential.
EXCLUDED_NAMES = {STAMP_NAME, "build_id.v"}

SCOPE = (
    "Scope: generates the Quartus build-identity stamp (DATE/GIT/SRC) consumed by "
    "sys/build_id.tcl for the CONF_STR V entry. SRC is a digest of the fit input "
    "files only; it does not hash the finished bitstream and does not prove that a "
    "fit ran, that the RBF was deployed, or that the OSD renders the string."
)


def iter_source_files(project: Path) -> list[Path]:
    files: list[Path] = []
    for path in sorted(project.rglob("*")):
        if not path.is_file() or path.is_symlink():
            continue
        rel = path.relative_to(project)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        if rel.name in EXCLUDED_NAMES or path.suffix in EXCLUDED_SUFFIXES:
            continue
        files.append(path)
    return files


def source_digest(project: Path) -> tuple[str, int]:
    h = hashlib.sha256()
    count = 0
    for path in iter_source_files(project):
        rel = path.relative_to(project).as_posix()
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(hashlib.sha256(path.read_bytes()).hexdigest().encode("ascii"))
        h.update(b"\n")
        count += 1
    return h.hexdigest(), count


def git_identity(repo: Path) -> str:
    def git(*args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["git", "-C", str(repo), *args], capture_output=True, text=True, timeout=30
        )

    # git searches parent directories, so a copied-out build slot nested under an
    # unrelated checkout would happily report that checkout's commit. Refuse any
    # identity that does not belong to the directory we were actually asked about.
    top = git("rev-parse", "--show-toplevel")
    if top.returncode != 0 or not top.stdout.strip():
        return "nogit"
    try:
        if Path(top.stdout.strip()).resolve() != repo.resolve():
            return "nogit"
    except OSError:
        return "nogit"

    rev = git("rev-parse", "--short=8", "HEAD")
    if rev.returncode != 0 or not rev.stdout.strip():
        return "nogit"
    short = rev.stdout.strip()
    dirty = git("status", "--porcelain", "--untracked-files=no")
    if dirty.returncode == 0 and dirty.stdout.strip():
        short += "D"
    return short


def build_stamp(project: Path, repo: Path, src_len: int) -> dict[str, str]:
    digest, count = source_digest(project)
    return {
        "DATE": time.strftime("%y%m%d"),
        "GIT": git_identity(repo),
        "SRC": digest[:src_len],
        "SRC_FULL": digest,
        "SRC_FILES": str(count),
        "UTC": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }


def build_id_string(stamp: dict[str, str]) -> str:
    return f"{stamp['DATE']}-{stamp['GIT']}-{stamp['SRC']}"


def render_stamp(stamp: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/gen_build_stamp.py — do not hand-edit.",
        "# Consumed by fpga/Plex_MiSTer/sys/build_id.tcl to define BUILD_ID/BUILD_DATE.",
    ]
    for key in ("DATE", "GIT", "SRC", "SRC_FULL", "SRC_FILES", "UTC"):
        lines.append(f"{key}={stamp[key]}")
    lines.append(f"BUILD_ID={build_id_string(stamp)}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Write the Plex Quartus build-identity stamp.")
    ap.add_argument("--project", default=str(DEFAULT_PROJECT), help="Quartus project directory")
    ap.add_argument("--repo", default=str(ROOT), help="git repository root for the GIT field")
    ap.add_argument("--src-len", type=int, default=6, help="hex digits of SRC kept in BUILD_ID")
    ap.add_argument("--json", action="store_true", help="print the stamp as JSON on stdout")
    ap.add_argument("--print-only", action="store_true", help="do not write the stamp file")
    ap.add_argument(
        "--require-git",
        action="store_true",
        help="fail when the git identity cannot be read (release/fit builds)",
    )
    args = ap.parse_args(argv)

    print(SCOPE)
    project = Path(args.project).resolve()
    if not (project / "Plex.qsf").is_file():
        print(f"BUILD_STAMP_RESULT=FAIL reason=not-a-plex-project path={project}")
        return 2
    if args.src_len < 4 or args.src_len > 64:
        print(f"BUILD_STAMP_RESULT=FAIL reason=bad-src-len value={args.src_len}")
        return 2

    stamp = build_stamp(project, Path(args.repo).resolve(), args.src_len)
    if args.require_git and stamp["GIT"] == "nogit":
        print("BUILD_STAMP_RESULT=FAIL reason=git-identity-unavailable")
        return 1

    if not args.print_only:
        (project / STAMP_NAME).write_text(render_stamp(stamp), encoding="utf-8")

    if args.json:
        print(json.dumps(stamp, sort_keys=True))
    print(
        "BUILD_STAMP_RESULT=OK"
        f" build_id={build_id_string(stamp)}"
        f" date={stamp['DATE']} git={stamp['GIT']} src={stamp['SRC']}"
        f" src_files={stamp['SRC_FILES']}"
        f" stamp={'(not written)' if args.print_only else project / STAMP_NAME}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
