#!/usr/bin/env python3
"""Generate build-time core identity stamp for RTL + host gates.

NOT hand-edited. Reads git HEAD (or CORE_IDENTITY_GIT_SHA / CORE_IDENTITY_PROVENANCE)
and writes:
  fpga/Plex_MiSTer/rtl/core_identity_stamp.svh
  assets/core_identity_stamp.json

Provenance = low 28 bits of the 40-bit git short object name (7 hex chars).
Path/capability bits are fixed for this writer (ddr_frame_store only):
  CAP_DDR_FRAME_STORE = 1
  CAP_SPI_LEGACY      = 0

Exit 0 on write. Exit 2 if git SHA cannot be resolved and no override given.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SVH = ROOT / "fpga" / "Plex_MiSTer" / "rtl" / "core_identity_stamp.svh"
JSON_OUT = ROOT / "assets" / "core_identity_stamp.json"

# ABI v1 packing (must match mailbox_abi_spec.hpp / ddr_frame_store.sv)
ABI_VER = 0x1
CAP_DDR = 1
CAP_SPI = 0
MAGIC = 0x504C5843  # "PLXC"


def resolve_git_sha() -> str:
    env = os.environ.get("CORE_IDENTITY_GIT_SHA", "").strip()
    if env:
        return env.lower().lstrip("0x")
    try:
        out = subprocess.check_output(
            ["git", "-C", str(ROOT), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if len(out) >= 7 and all(c in "0123456789abcdef" for c in out.lower()):
            return out.lower()
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    return ""


def provenance_28(sha: str) -> int:
    override = os.environ.get("CORE_IDENTITY_PROVENANCE", "").strip()
    if override:
        return int(override, 0) & 0x0FFFFFFF
    # First 7 hex chars of object name → 28 bits.
    return int(sha[:7], 16) & 0x0FFFFFFF


def pack_hi(prov: int) -> int:
    """Upper 32 bits of the 64-bit mailbox word."""
    # [27:0] provenance, [28]=CAP_DDR, [29]=CAP_SPI, [31:30]=ABI
    return (
        (prov & 0x0FFFFFFF)
        | ((CAP_DDR & 1) << 28)
        | ((CAP_SPI & 1) << 29)
        | ((ABI_VER & 3) << 30)
    )


def main() -> int:
    sha = resolve_git_sha()
    if not sha:
        print(
            "gen_core_identity_stamp: cannot resolve git SHA "
            "(set CORE_IDENTITY_GIT_SHA or run inside a git work tree)",
            file=sys.stderr,
        )
        return 2
    prov = provenance_28(sha)
    hi = pack_hi(prov)
    word = (hi << 32) | MAGIC

    svh = f"""// GENERATED by scripts/gen_core_identity_stamp.py — do not hand-edit.
// SOURCE_GIT={sha}
// Regenerate: python3 scripts/gen_core_identity_stamp.py
`ifndef CORE_IDENTITY_STAMP_SVH
`define CORE_IDENTITY_STAMP_SVH
localparam [27:0] CORE_IDENTITY_PROVENANCE_LP = 28'h{prov:07X};
localparam [0:0]  CORE_IDENTITY_CAP_DDR_LP    = 1'b{CAP_DDR};
localparam [0:0]  CORE_IDENTITY_CAP_SPI_LP    = 1'b{CAP_SPI};
localparam [1:0]  CORE_IDENTITY_ABI_LP        = 2'd{ABI_VER};
localparam [31:0] CORE_IDENTITY_MAGIC_LP      = 32'h{MAGIC:08X};
localparam [31:0] CORE_IDENTITY_HI_LP         = 32'h{hi:08X};
`endif
"""
    SVH.parent.mkdir(parents=True, exist_ok=True)
    SVH.write_text(svh)
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps(
            {
                "magic": f"0x{MAGIC:08X}",
                "magic_ascii": "PLXC",
                "offset_from_doorbell": "0x130",
                "source_git": sha,
                "provenance_28": f"0x{prov:07X}",
                "cap_ddr_frame_store": CAP_DDR,
                "cap_spi_legacy": CAP_SPI,
                "abi_version": ABI_VER,
                "hi32": f"0x{hi:08X}",
                "word64": f"0x{word:016X}",
                "product_phys_example": "0x300FF130",
            },
            indent=2,
        )
        + "\n"
    )
    print(f"gen_core_identity_stamp: SOURCE_GIT={sha} provenance=0x{prov:07X}")
    print(f"  wrote {SVH.relative_to(ROOT)}")
    print(f"  wrote {JSON_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
