#!/usr/bin/env python3
"""Generate rtl/plex_rbf_build_id_params.vh from git + files.qip.

Run before Quartus fit (and optionally from build_rbf_remote). Static — no fit.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT_DEFAULT = Path(__file__).resolve().parents[1]
_QIP = re.compile(
    r"set_global_assignment\s+-name\s+(?:SYSTEMVERILOG_FILE|VERILOG_FILE|VHDL_FILE|SDC_FILE)\s+(\S+)",
    re.I,
)


def git(root: Path, *args: str) -> str:
    p = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    return (p.stdout or "").strip() if p.returncode == 0 else ""


def qip_count(root: Path) -> int:
    qip = root / "fpga" / "Plex_MiSTer" / "files.qip"
    if not qip.is_file():
        return 0
    n = 0
    for line in qip.read_text(errors="replace").splitlines():
        s = line.strip()
        if not s or s.startswith("//") or s.startswith("#"):
            continue
        if _QIP.search(s):
            n += 1
    return n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(ROOT_DEFAULT))
    ap.add_argument(
        "--out",
        default="",
        help="default: fpga/Plex_MiSTer/rtl/plex_rbf_build_id_params.vh",
    )
    args = ap.parse_args()
    root = Path(args.root).resolve()
    out = (
        Path(args.out)
        if args.out
        else root / "fpga" / "Plex_MiSTer" / "rtl" / "plex_rbf_build_id_params.vh"
    )
    commit = git(root, "rev-parse", "HEAD")
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        print(f"GEN_RBF_BUILD_ID_FAIL bad commit {commit!r}", file=sys.stderr)
        print("true rc=2")
        return 2
    dirty = bool(git(root, "status", "--porcelain"))
    prefix = commit[:8]
    try:
        prefix_u32 = int(prefix, 16)
    except ValueError:
        print(f"GEN_RBF_BUILD_ID_FAIL bad prefix {prefix}", file=sys.stderr)
        print("true rc=2")
        return 2
    qc = qip_count(root)
    body = f"""// Auto-generated by scripts/gen_rbf_build_id_vh.py — do not hand-edit.
// commit={commit} dirty={int(dirty)} qip_count={qc}
`ifndef PLEX_RBF_BUILD_ID_PARAMS_VH
`define PLEX_RBF_BUILD_ID_PARAMS_VH
`define PLEX_RBF_COMMIT_PREFIX 32'h{prefix_u32:08X}
`define PLEX_RBF_GIT_DIRTY     1'b{1 if dirty else 0}
`define PLEX_RBF_QIP_COUNT     16'd{qc}
`endif
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body)
    print(f"GEN_RBF_BUILD_ID_OK path={out}")
    print(f"  commit={commit}")
    print(f"  COMMIT_PREFIX=0x{prefix_u32:08x} dirty={int(dirty)} qip_count={qc}")
    print("EXECUTED gen=1")
    print("true rc=0")
    return 0


if __name__ == "__main__":
    sys.exit(main())
