// Testbench wrapper: exposes h264_intra_nb_ctx and h264_intra4x4_pred for
// full-width reconstructed-neighbour context verification.
module h264_intra_nb_ctx_tb (
    input  wire        clk,
    input  wire        reset,
    input  wire [7:0]  mb_x,
    input  wire [7:0]  mb_y,
    input  wire [7:0]  mb_width,
    input  wire [15:0] first_mb_in_slice,
    input  wire        mb_start,
    input  wire [3:0]  block_idx,
    input  wire [3:0]  pred_mode,
    input  wire        block_valid,
    input  wire        mb_commit,
    input  wire [7:0]  recon_in [0:15],
    input  wire [7:0]  recon_y_mb [0:255],
    input  wire [7:0]  recon_u_mb [0:63],
    input  wire [7:0]  recon_v_mb [0:63],
    output wire [3:0]  used_mode,
    output wire [7:0]  pred [0:15],
    output wire [7:0]  ctx_above [0:7],
    output wire [7:0]  ctx_left [0:3],
    output wire [7:0]  ctx_top_left,
    output wire        ctx_has_above,
    output wire        ctx_has_left,
    output wire        ctx_has_above_right,
    output wire        ctx_mb_avail_left,
    output wire        ctx_mb_avail_top,
    output wire        ctx_mb_avail_topright,
    output wire        ctx_mb_avail_topleft,
    output wire [7:0]  ctx_nb_top [0:15],
    output wire [7:0]  ctx_nb_left [0:15],
    output wire [7:0]  ctx_nb_topleft,
    output wire [7:0]  ctx_nb_topright [0:3],
    output wire [7:0]  ctx_chroma_u_above [0:7],
    output wire [7:0]  ctx_chroma_v_above [0:7],
    output wire [7:0]  ctx_chroma_u_left [0:7],
    output wire [7:0]  ctx_chroma_v_left [0:7],
    output wire [7:0]  ctx_chroma_u_top_left,
    output wire [7:0]  ctx_chroma_v_top_left,
    output wire        ctx_has_chroma_above,
    output wire        ctx_has_chroma_left,
    output wire        ctx_busy
);
    h264_intra_nb_ctx #(
        .MB_WIDTH_MAX(39),
        .MB_WIDTH_DEFAULT(39)
    ) u_nb_ctx (
        .clk(clk),
        .reset(reset),
        .mb_x(mb_x),
        .mb_y(mb_y),
        .mb_width(mb_width),
        .first_mb_in_slice(first_mb_in_slice),
        .mb_start(mb_start),
        .block_idx(block_idx),
        .block_valid(block_valid),
        .recon_pixels(recon_in),
        .mb_commit(mb_commit),
        .recon_y_mb(recon_y_mb),
        .recon_u_mb(recon_u_mb),
        .recon_v_mb(recon_v_mb),
        .above(ctx_above),
        .left(ctx_left),
        .top_left(ctx_top_left),
        .has_above(ctx_has_above),
        .has_left(ctx_has_left),
        .has_above_right(ctx_has_above_right),
        .mb_avail_left(ctx_mb_avail_left),
        .mb_avail_top(ctx_mb_avail_top),
        .mb_avail_topright(ctx_mb_avail_topright),
        .mb_avail_topleft(ctx_mb_avail_topleft),
        .nb_top(ctx_nb_top),
        .nb_left(ctx_nb_left),
        .nb_topleft(ctx_nb_topleft),
        .nb_topright(ctx_nb_topright),
        .chroma_u_above(ctx_chroma_u_above),
        .chroma_v_above(ctx_chroma_v_above),
        .chroma_u_left(ctx_chroma_u_left),
        .chroma_v_left(ctx_chroma_v_left),
        .chroma_u_top_left(ctx_chroma_u_top_left),
        .chroma_v_top_left(ctx_chroma_v_top_left),
        .has_chroma_above(ctx_has_chroma_above),
        .has_chroma_left(ctx_has_chroma_left),
        .busy(ctx_busy)
    );

    h264_intra4x4_pred u_pred (
        .mode(pred_mode),
        .above(ctx_above),
        .left(ctx_left),
        .top_left(ctx_top_left),
        .has_above(ctx_has_above),
        .has_left(ctx_has_left),
        .used_mode(used_mode),
        .pred(pred)
    );
endmodule
