#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
mkdir -p build/p3_golden
IN="tests/fixtures/p3_host_recon/plex_real_baseline_320x240_1f.264"
REF="tests/fixtures/p3_host_recon/mb0_luma_v1.json"
OUT_A="build/p3_golden/mb0_a.json"
OUT_B="build/p3_golden/mb0_b.json"
SEQ_A="build/p3_golden/sequence_a.json"
SEQ_B="build/p3_golden/sequence_b.json"
WCAP_SEQ="build/p3_golden/wcap_sequence.json"
SEQ_624="build/p3_golden/sequence_624.json"
SEQ_IN="tests/fixtures/p3_inter_pred/plex_inter_p16_baseline_320x240_12f.264"
SEQ_FIXTURE="tests/fixtures/p3_multinal/plex_inter_p16_sequence_v1.json"
SEQ_624_IN="tests/fixtures/p3_inter_pred/plex_inter_p16_baseline_624x480_12f.264"
SEQ_624_FIXTURE="tests/fixtures/p3_multinal/plex_inter_p16_624x480_sequence_v1.json"
WCAP_IN="tests/fixtures/p3_multinal/wcap_residual14_idr_plus_p.264"
WCAP_FIXTURE="tests/fixtures/p3_multinal/wcap_residual14_idr_plus_p_sequence_v1.json"
./build/extract_h264_golden --input "$IN" --mb 0 --output "$OUT_A" --verify-mb0-reference "$REF"
./build/extract_h264_golden --input "$IN" --mb 0 --output "$OUT_B" --verify-mb0-reference "$REF"
./build/extract_h264_golden --sequence --input "$SEQ_IN" --output "$SEQ_A"
./build/extract_h264_golden --sequence --input "$SEQ_IN" --output "$SEQ_B"
./build/extract_h264_golden --sequence --input "$SEQ_624_IN" --output "$SEQ_624"
./build/extract_h264_golden --sequence --input "$WCAP_IN" --output "$WCAP_SEQ"
cmp -s "$OUT_A" "$OUT_B"
cmp -s "$SEQ_A" "$SEQ_B"
cmp -s "$SEQ_A" "$SEQ_FIXTURE"
cmp -s "$SEQ_624" "$SEQ_624_FIXTURE"
cmp -s "$WCAP_SEQ" "$WCAP_FIXTURE"
grep -q '"format": "misterplex.p3.mb_golden.v1"' "$OUT_A"
grep -q '"nA": {"available": false, "total_coeff": -1}' "$OUT_A"
grep -q '"predicted_nC": 0' "$OUT_A"
grep -q '"coeff_token_table_name": "nC_0_1"' "$OUT_A"
grep -q '"first_residual_checksum8_hex": "0x14"' "$OUT_A"
grep -q '"first_recon_signature8_hex": "0x3b"' "$OUT_A"
grep -q '"first_pred_only_signature8_hex": "0x00"' "$OUT_A"
grep -q '"first_one_cycle_delayed_signature8_hex": "0x00"' "$OUT_A"
grep -q '"latency_contract": "Consumers must align residual valid/data with prediction' "$OUT_A"
grep -q '"frame_plane_golden": {"format": "misterplex.p3.frame_planes_golden.v1"' "$OUT_A"
grep -q '"compose_with": "misterplex.p3.frame_planes_compare.v1"' "$OUT_A"
grep -q '"format": "misterplex.p3.nal_sequence.v1"' "$SEQ_A"
grep -q '"nal_count": 15, "vcl": 12, "idr": 1, "non_idr": 11, "i_slices": 1, "p_slices": 11' "$SEQ_A"
grep -q '"coded_width": 624, "coded_height": 480' "$SEQ_624"
grep -q '"requires_idle_between_vcl": true' "$SEQ_A"
grep -q '"ioctl_injection": "assert ioctl_download, pulse ioctl_wr once per byte on ioctl_dout' "$SEQ_A"
grep -q '"slice_kind": "P"' "$SEQ_A"
grep -q '"nal_count": 5, "vcl": 2, "idr": 1, "non_idr": 1, "i_slices": 1, "p_slices": 1' "$WCAP_SEQ"
echo "test_h264_golden_extractor: OK deterministic MB0 + multi-NAL IDR/P sequence; latency red-check pred-only=0x00 vs recon=0x3b"
